spring:
  datasource:
    url: jdbc:postgresql://hzung.sontran.us:2345/motorbike
    #url: jdbc:postgresql://localhost:5432/motorbike
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

# The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect : org.hibernate.dialect.PostgreSQLDialect
        jdbc: lob.non_contextual_creation=true
        ddl-auto : update
    show-sql : true

# Kafka
  kafka:
    bootstrap-servers: localhost:9092
    enable: true

# Specify the path of the OpenAPI documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

server:
   forward-headers-strategy: framework

